server:
  port: 8081

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

spring:
  application:
    name: user-service
  main:
    banner-mode: "off"
  data:
    mongodb:
      uri: mongodb+srv://productsuser:productspassword@cluster0.wzm30.gcp.mongodb.net/?retryWrites=true&w=majority
      database: test