server:
  port: 8081

crypto:
  key: 1234567891234567

auth:
  permitAll: /users/v1/private-key-jwt,/users/v1/signup,/users/v1,/accounts/v1/activate,/auth/v1/machine/token,/passwords/v1,/passwords/v1/reset_initiate,/passwords/v1/reset_submit,/tokens/v1,/users/v1/*
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

spring:
  application:
    name: auth-service
  main:
    banner-mode: "off"
  data:
    mongodb:
      #bigtree.authz@gmail.com
      uri: mongodb+srv://bigtreeauthz:SvGkhNpbVtJaY0Q2@bigtreeauthzcluster.ajaigyp.mongodb.net/?retryWrites=true&w=majority&appName=BigtreeAuthzCluster
      database: prod
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: noreply.zcoop@gmail.com
    password: akubyctoglgqakub 
    port: 587
    debug: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false